"""<message>

Revision ID: e24d77571e43
Revises: 6277fa930372
Create Date: 2024-03-12 19:59:47.179548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e24d77571e43'
down_revision = '6277fa930372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
