"""Added major restricted and comm intensive columns to the Course table

Revision ID: 6277fa930372
Revises: c959c263997f
Create Date: 2024-02-02 21:45:28.304167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6277fa930372'
down_revision = 'c959c263997f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('communication_intensive', sa.BOOLEAN(), nullable=True))
    op.add_column('course', sa.Column('major_restricted', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'major_restricted')
    op.drop_column('course', 'communication_intensive')
    # ### end Alembic commands ###
